// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: adU29zJd9uLGW9TewABBsV
// Component: lKMH_lDVGHXv
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_fusion_lab.module.css"; // plasmic-import: adU29zJd9uLGW9TewABBsV/projectcss
import sty from "./PlasmicPopUpGallery.module.css"; // plasmic-import: lKMH_lDVGHXv/css
import chevronLeftBlack24Dp2MYaRzqAvvItW from "./images/chevronLeftBlack24Dp2.svg"; // plasmic-import: mYaRZQAvvItW/picture
import chevronRightBlack24Dp1HPr2YtSdR4R from "./images/chevronRightBlack24Dp1.svg"; // plasmic-import: hPr2YTSd-R4R/picture
import closeWhite36Dp1RrVeLvbYQpRj from "./images/closeWhite36Dp1.svg"; // plasmic-import: RrVeLvbYQpRJ/picture

createPlasmicElementProxy;

export const PlasmicPopUpGallery__VariantProps = new Array("popUpVariants");

export const PlasmicPopUpGallery__ArgProps = new Array();

const $$ = {};

function PlasmicPopUpGallery__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "popUpVariants",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.popUpVariants
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootpopUpVariants_activity1]: hasVariant(
            $state,
            "popUpVariants",
            "activity1"
          ),
          [sty.rootpopUpVariants_activity2]: hasVariant(
            $state,
            "popUpVariants",
            "activity2"
          )
        }
      )}
    >
      <div
        data-plasmic-name={"lightboxDisplay"}
        data-plasmic-override={overrides.lightboxDisplay}
        className={classNames(projectcss.all, sty.lightboxDisplay)}
      >
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox, {
            [sty.freeBoxpopUpVariants_activity1]: hasVariant(
              $state,
              "popUpVariants",
              "activity1"
            )
          })}
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img___18Uwh)}
            displayHeight={"56px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"47px"}
            loading={"lazy"}
            src={{
              src: chevronLeftBlack24Dp2MYaRzqAvvItW,
              fullWidth: 47,
              fullHeight: 56,
              aspectRatio: 0.839286
            }}
          />

          <div
            data-plasmic-name={"display"}
            data-plasmic-override={overrides.display}
            className={classNames(projectcss.all, sty.display)}
          >
            <div
              data-plasmic-name={"maskGroup"}
              data-plasmic-override={overrides.maskGroup}
              className={classNames(projectcss.all, sty.maskGroup)}
            >
              <div
                data-plasmic-name={"image"}
                data-plasmic-override={overrides.image}
                className={classNames(projectcss.all, sty.image)}
              />
            </div>
            <div
              data-plasmic-name={"maskGroup2"}
              data-plasmic-override={overrides.maskGroup2}
              className={classNames(projectcss.all, sty.maskGroup2)}
            >
              <div
                data-plasmic-name={"image2"}
                data-plasmic-override={overrides.image2}
                className={classNames(projectcss.all, sty.image2)}
              />

              <div
                data-plasmic-name={
                  "extendingFromTheSkateParkUsersWillFlowFromRampsToAnOpenAreaAdornedWithGraffitiCoveredColumnsHereOneCanRelaxWhileLookingAtTheArtOrIndulgeInClimbingConvenientlyCloseToHomeTheClimbingWallIntegratedOntoReinforcedWallsSupportingRampsMaintainsPrivacyWithCoveredUpperSidesAndAllowsNaturalLightThroughCarefullyPlacedOpeningsWellLitForNighttimeUseTheSpaceIncludesAFewParkingSpotsWithPowerStationsForElectricVehiclesEnhancingAccessibilityAndConvenience"
                }
                data-plasmic-override={
                  overrides.extendingFromTheSkateParkUsersWillFlowFromRampsToAnOpenAreaAdornedWithGraffitiCoveredColumnsHereOneCanRelaxWhileLookingAtTheArtOrIndulgeInClimbingConvenientlyCloseToHomeTheClimbingWallIntegratedOntoReinforcedWallsSupportingRampsMaintainsPrivacyWithCoveredUpperSidesAndAllowsNaturalLightThroughCarefullyPlacedOpeningsWellLitForNighttimeUseTheSpaceIncludesAFewParkingSpotsWithPowerStationsForElectricVehiclesEnhancingAccessibilityAndConvenience
                }
                className={classNames(
                  projectcss.all,
                  sty.extendingFromTheSkateParkUsersWillFlowFromRampsToAnOpenAreaAdornedWithGraffitiCoveredColumnsHereOneCanRelaxWhileLookingAtTheArtOrIndulgeInClimbingConvenientlyCloseToHomeTheClimbingWallIntegratedOntoReinforcedWallsSupportingRampsMaintainsPrivacyWithCoveredUpperSidesAndAllowsNaturalLightThroughCarefullyPlacedOpeningsWellLitForNighttimeUseTheSpaceIncludesAFewParkingSpotsWithPowerStationsForElectricVehiclesEnhancingAccessibilityAndConvenience
                )}
              >
                <div
                  data-plasmic-name={"text"}
                  data-plasmic-override={overrides.text}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text
                  )}
                >
                  {
                    "Extending from the skate park, users will flow from ramps to an open area adorned with graffiti-covered columns. Here, one can relax while looking at the art or indulge in climbing, conveniently close to home. The climbing wall, integrated onto reinforced walls supporting ramps, maintains privacy with covered upper sides and allows natural light through carefully placed openings. Well-lit for nighttime use, the space includes a few parking spots with power stations for electric vehicles, enhancing accessibility and convenience."
                  }
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"maskGroup3"}
              data-plasmic-override={overrides.maskGroup3}
              className={classNames(projectcss.all, sty.maskGroup3)}
            >
              <div
                data-plasmic-name={"image3"}
                data-plasmic-override={overrides.image3}
                className={classNames(projectcss.all, sty.image3)}
              />
            </div>
            <div
              data-plasmic-name={"maskGroup4"}
              data-plasmic-override={overrides.maskGroup4}
              className={classNames(projectcss.all, sty.maskGroup4)}
            >
              <div
                data-plasmic-name={"image4"}
                data-plasmic-override={overrides.image4}
                className={classNames(projectcss.all, sty.image4)}
              />
            </div>
            <div
              data-plasmic-name={"caption"}
              data-plasmic-override={overrides.caption}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.caption
              )}
            >
              {"Climbing Wall"}
            </div>
          </div>
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__yCs8F)}
            displayHeight={"56px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"47px"}
            loading={"lazy"}
            src={{
              src: chevronRightBlack24Dp1HPr2YtSdR4R,
              fullWidth: 47,
              fullHeight: 56,
              aspectRatio: 0.839286
            }}
          />
        </div>
        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__hj0Qc)}
          displayHeight={"36px"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"36px"}
          loading={"lazy"}
          src={{
            src: closeWhite36Dp1RrVeLvbYQpRj,
            fullWidth: 36,
            fullHeight: 36,
            aspectRatio: 1
          }}
        />
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "lightboxDisplay",
    "freeBox",
    "display",
    "maskGroup",
    "image",
    "maskGroup2",
    "image2",
    "extendingFromTheSkateParkUsersWillFlowFromRampsToAnOpenAreaAdornedWithGraffitiCoveredColumnsHereOneCanRelaxWhileLookingAtTheArtOrIndulgeInClimbingConvenientlyCloseToHomeTheClimbingWallIntegratedOntoReinforcedWallsSupportingRampsMaintainsPrivacyWithCoveredUpperSidesAndAllowsNaturalLightThroughCarefullyPlacedOpeningsWellLitForNighttimeUseTheSpaceIncludesAFewParkingSpotsWithPowerStationsForElectricVehiclesEnhancingAccessibilityAndConvenience",
    "text",
    "maskGroup3",
    "image3",
    "maskGroup4",
    "image4",
    "caption"
  ],

  lightboxDisplay: [
    "lightboxDisplay",
    "freeBox",
    "display",
    "maskGroup",
    "image",
    "maskGroup2",
    "image2",
    "extendingFromTheSkateParkUsersWillFlowFromRampsToAnOpenAreaAdornedWithGraffitiCoveredColumnsHereOneCanRelaxWhileLookingAtTheArtOrIndulgeInClimbingConvenientlyCloseToHomeTheClimbingWallIntegratedOntoReinforcedWallsSupportingRampsMaintainsPrivacyWithCoveredUpperSidesAndAllowsNaturalLightThroughCarefullyPlacedOpeningsWellLitForNighttimeUseTheSpaceIncludesAFewParkingSpotsWithPowerStationsForElectricVehiclesEnhancingAccessibilityAndConvenience",
    "text",
    "maskGroup3",
    "image3",
    "maskGroup4",
    "image4",
    "caption"
  ],

  freeBox: [
    "freeBox",
    "display",
    "maskGroup",
    "image",
    "maskGroup2",
    "image2",
    "extendingFromTheSkateParkUsersWillFlowFromRampsToAnOpenAreaAdornedWithGraffitiCoveredColumnsHereOneCanRelaxWhileLookingAtTheArtOrIndulgeInClimbingConvenientlyCloseToHomeTheClimbingWallIntegratedOntoReinforcedWallsSupportingRampsMaintainsPrivacyWithCoveredUpperSidesAndAllowsNaturalLightThroughCarefullyPlacedOpeningsWellLitForNighttimeUseTheSpaceIncludesAFewParkingSpotsWithPowerStationsForElectricVehiclesEnhancingAccessibilityAndConvenience",
    "text",
    "maskGroup3",
    "image3",
    "maskGroup4",
    "image4",
    "caption"
  ],

  display: [
    "display",
    "maskGroup",
    "image",
    "maskGroup2",
    "image2",
    "extendingFromTheSkateParkUsersWillFlowFromRampsToAnOpenAreaAdornedWithGraffitiCoveredColumnsHereOneCanRelaxWhileLookingAtTheArtOrIndulgeInClimbingConvenientlyCloseToHomeTheClimbingWallIntegratedOntoReinforcedWallsSupportingRampsMaintainsPrivacyWithCoveredUpperSidesAndAllowsNaturalLightThroughCarefullyPlacedOpeningsWellLitForNighttimeUseTheSpaceIncludesAFewParkingSpotsWithPowerStationsForElectricVehiclesEnhancingAccessibilityAndConvenience",
    "text",
    "maskGroup3",
    "image3",
    "maskGroup4",
    "image4",
    "caption"
  ],

  maskGroup: ["maskGroup", "image"],
  image: ["image"],
  maskGroup2: [
    "maskGroup2",
    "image2",
    "extendingFromTheSkateParkUsersWillFlowFromRampsToAnOpenAreaAdornedWithGraffitiCoveredColumnsHereOneCanRelaxWhileLookingAtTheArtOrIndulgeInClimbingConvenientlyCloseToHomeTheClimbingWallIntegratedOntoReinforcedWallsSupportingRampsMaintainsPrivacyWithCoveredUpperSidesAndAllowsNaturalLightThroughCarefullyPlacedOpeningsWellLitForNighttimeUseTheSpaceIncludesAFewParkingSpotsWithPowerStationsForElectricVehiclesEnhancingAccessibilityAndConvenience",
    "text"
  ],

  image2: ["image2"],
  extendingFromTheSkateParkUsersWillFlowFromRampsToAnOpenAreaAdornedWithGraffitiCoveredColumnsHereOneCanRelaxWhileLookingAtTheArtOrIndulgeInClimbingConvenientlyCloseToHomeTheClimbingWallIntegratedOntoReinforcedWallsSupportingRampsMaintainsPrivacyWithCoveredUpperSidesAndAllowsNaturalLightThroughCarefullyPlacedOpeningsWellLitForNighttimeUseTheSpaceIncludesAFewParkingSpotsWithPowerStationsForElectricVehiclesEnhancingAccessibilityAndConvenience:
    [
      "extendingFromTheSkateParkUsersWillFlowFromRampsToAnOpenAreaAdornedWithGraffitiCoveredColumnsHereOneCanRelaxWhileLookingAtTheArtOrIndulgeInClimbingConvenientlyCloseToHomeTheClimbingWallIntegratedOntoReinforcedWallsSupportingRampsMaintainsPrivacyWithCoveredUpperSidesAndAllowsNaturalLightThroughCarefullyPlacedOpeningsWellLitForNighttimeUseTheSpaceIncludesAFewParkingSpotsWithPowerStationsForElectricVehiclesEnhancingAccessibilityAndConvenience",
      "text"
    ],

  text: ["text"],
  maskGroup3: ["maskGroup3", "image3"],
  image3: ["image3"],
  maskGroup4: ["maskGroup4", "image4"],
  image4: ["image4"],
  caption: ["caption"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPopUpGallery__ArgProps,
          internalVariantPropNames: PlasmicPopUpGallery__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPopUpGallery__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPopUpGallery";
  } else {
    func.displayName = `PlasmicPopUpGallery.${nodeName}`;
  }
  return func;
}

export const PlasmicPopUpGallery = Object.assign(
  // Top-level PlasmicPopUpGallery renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    lightboxDisplay: makeNodeComponent("lightboxDisplay"),
    freeBox: makeNodeComponent("freeBox"),
    display: makeNodeComponent("display"),
    maskGroup: makeNodeComponent("maskGroup"),
    image: makeNodeComponent("image"),
    maskGroup2: makeNodeComponent("maskGroup2"),
    image2: makeNodeComponent("image2"),
    extendingFromTheSkateParkUsersWillFlowFromRampsToAnOpenAreaAdornedWithGraffitiCoveredColumnsHereOneCanRelaxWhileLookingAtTheArtOrIndulgeInClimbingConvenientlyCloseToHomeTheClimbingWallIntegratedOntoReinforcedWallsSupportingRampsMaintainsPrivacyWithCoveredUpperSidesAndAllowsNaturalLightThroughCarefullyPlacedOpeningsWellLitForNighttimeUseTheSpaceIncludesAFewParkingSpotsWithPowerStationsForElectricVehiclesEnhancingAccessibilityAndConvenience:
      makeNodeComponent(
        "extendingFromTheSkateParkUsersWillFlowFromRampsToAnOpenAreaAdornedWithGraffitiCoveredColumnsHereOneCanRelaxWhileLookingAtTheArtOrIndulgeInClimbingConvenientlyCloseToHomeTheClimbingWallIntegratedOntoReinforcedWallsSupportingRampsMaintainsPrivacyWithCoveredUpperSidesAndAllowsNaturalLightThroughCarefullyPlacedOpeningsWellLitForNighttimeUseTheSpaceIncludesAFewParkingSpotsWithPowerStationsForElectricVehiclesEnhancingAccessibilityAndConvenience"
      ),
    text: makeNodeComponent("text"),
    maskGroup3: makeNodeComponent("maskGroup3"),
    image3: makeNodeComponent("image3"),
    maskGroup4: makeNodeComponent("maskGroup4"),
    image4: makeNodeComponent("image4"),
    caption: makeNodeComponent("caption"),
    // Metadata about props expected for PlasmicPopUpGallery
    internalVariantProps: PlasmicPopUpGallery__VariantProps,
    internalArgProps: PlasmicPopUpGallery__ArgProps
  }
);

export default PlasmicPopUpGallery;
/* prettier-ignore-end */
