// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: adU29zJd9uLGW9TewABBsV
// Component: kcOa2EjH_22k
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import VotingCard from "../../VotingCard"; // plasmic-import: oAGE1uzhgryh/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_fusion_lab.module.css"; // plasmic-import: adU29zJd9uLGW9TewABBsV/projectcss
import sty from "./PlasmicModelViewer.module.css"; // plasmic-import: kcOa2EjH_22k/css
import QuestionIcon from "./icons/PlasmicIcon__Question"; // plasmic-import: K0QTQ9gFlm8R/icon
import IcMoreVertBlack24PxIcon from "./icons/PlasmicIcon__IcMoreVertBlack24Px"; // plasmic-import: f0QTkUbbBeM7/icon
import IcReplyBlack24PxIcon from "./icons/PlasmicIcon__IcReplyBlack24Px"; // plasmic-import: ZNCsxgaarB5y/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: WAleb0vztUX5/icon
import card20EhPfyfb01DlD from "./images/card20.svg"; // plasmic-import: EHPfyfb01DlD/picture
import card19Tp7NtoQxp1Tg from "./images/card19.svg"; // plasmic-import: tp7ntoQXP1tg/picture
import card18DqIos4XrT44M from "./images/card18.svg"; // plasmic-import: DQIos4xrT44M/picture
import card17S1836A8Apxva from "./images/card17.svg"; // plasmic-import: S1836a8Apxva/picture
import card16GVny4Zq83G7 from "./images/card16.svg"; // plasmic-import: gVNY4-ZQ83G7/picture
import card153T5Hxzs8V4 from "./images/card15.svg"; // plasmic-import: _-3t5hxzs8V4/picture
import card14Q34VvSOLp6 from "./images/card14.svg"; // plasmic-import: q34Vv_s-OLp6/picture
import card13KtjFKvbQn3QE from "./images/card13.svg"; // plasmic-import: KtjFKvbQN3qE/picture
import card12Hw0LkK0NawE9 from "./images/card12.svg"; // plasmic-import: hw0LkK0nawE9/picture
import card11Go3TukYtRysD from "./images/card11.svg"; // plasmic-import: GO3TUKYtRysD/picture

createPlasmicElementProxy;

export const PlasmicModelViewer__VariantProps = new Array();

export const PlasmicModelViewer__ArgProps = new Array();

const $$ = {};

function PlasmicModelViewer__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"figmaPaste"}
        data-plasmic-override={overrides.figmaPaste}
        className={classNames(projectcss.all, sty.figmaPaste)}
      >
        <div
          data-plasmic-name={"headerAndText"}
          data-plasmic-override={overrides.headerAndText}
          className={classNames(projectcss.all, sty.headerAndText)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__x3Vi5
            )}
          >
            {"Model Viewer"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__hQfvk
            )}
          >
            {
              "Here you can walk around the design and experience every little detail of it!"
            }
          </div>
        </div>
        <div
          data-plasmic-name={"navigationBar"}
          data-plasmic-override={overrides.navigationBar}
          className={classNames(projectcss.all, sty.navigationBar)}
        >
          <NavigationBar
            data-plasmic-name={"navigationBar2"}
            data-plasmic-override={overrides.navigationBar2}
            brand={null}
            className={classNames("__wab_instance", sty.navigationBar2)}
            closeButton={null}
            itemsGap={8}
            menuItems={null}
            openButton={
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__mIn39)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={"https://static1.plasmic.app/menu.svg"}
              />
            }
            responsiveBreakpoint={768}
          />

          <QuestionIcon
            className={classNames(projectcss.all, sty.svg__jsuTj)}
            role={"img"}
          />
        </div>
        <p.Stack
          as={"div"}
          data-plasmic-name={"frame8722"}
          data-plasmic-override={overrides.frame8722}
          hasGap={true}
          className={classNames(projectcss.all, sty.frame8722)}
        >
          <div
            data-plasmic-name={"navigationButton"}
            data-plasmic-override={overrides.navigationButton}
            className={classNames(projectcss.all, sty.navigationButton)}
          >
            <div
              data-plasmic-name={"rectangle7"}
              data-plasmic-override={overrides.rectangle7}
              className={classNames(projectcss.all, sty.rectangle7)}
            />
          </div>
        </p.Stack>
        <div
          data-plasmic-name={"group"}
          data-plasmic-override={overrides.group}
          className={classNames(projectcss.all, sty.group)}
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__m5JC6)}
            displayHeight={"60px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"400px"}
            loading={"lazy"}
            src={{
              src: card20EhPfyfb01DlD,
              fullWidth: 400,
              fullHeight: 60,
              aspectRatio: 6.666667
            }}
          />

          <div
            data-plasmic-name={"settings"}
            data-plasmic-override={overrides.settings}
            className={classNames(projectcss.all, sty.settings)}
          >
            <div
              data-plasmic-name={"settings2"}
              data-plasmic-override={overrides.settings2}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings2
              )}
            >
              {"Group C is the best!"}
            </div>
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px)}
          >
            <IcMoreVertBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__pmyNn)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px2"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px2}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px2)}
          >
            <IcReplyBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__viY9M)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"group2"}
            data-plasmic-override={overrides.group2}
            className={classNames(projectcss.all, sty.group2)}
          >
            <div
              data-plasmic-name={"settings3"}
              data-plasmic-override={overrides.settings3}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings3
              )}
            >
              {"notoyrobots"}
            </div>
            <div
              data-plasmic-name={"settings4"}
              data-plasmic-override={overrides.settings4}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings4
              )}
            >
              {"2 hours ago"}
            </div>
          </div>
          <div
            data-plasmic-name={"group3"}
            data-plasmic-override={overrides.group3}
            className={classNames(projectcss.all, sty.group3)}
          >
            <div
              data-plasmic-name={"settings5"}
              data-plasmic-override={overrides.settings5}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings5
              )}
            >
              {"1.5k"}
            </div>
            <Vector2Icon
              className={classNames(projectcss.all, sty.svg___6Ia1T)}
              role={"img"}
            />

            <Vector2Icon
              className={classNames(projectcss.all, sty.svg___4C4Gl)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"abefore"}
            data-plasmic-override={overrides.abefore}
            className={classNames(projectcss.all, sty.abefore)}
          />
        </div>
        <div
          data-plasmic-name={"group4"}
          data-plasmic-override={overrides.group4}
          className={classNames(projectcss.all, sty.group4)}
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__oKbdb)}
            displayHeight={"60px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"400px"}
            loading={"lazy"}
            src={{
              src: card19Tp7NtoQxp1Tg,
              fullWidth: 400,
              fullHeight: 60,
              aspectRatio: 6.666667
            }}
          />

          <div
            data-plasmic-name={"settings6"}
            data-plasmic-override={overrides.settings6}
            className={classNames(projectcss.all, sty.settings6)}
          >
            <div
              data-plasmic-name={"settings7"}
              data-plasmic-override={overrides.settings7}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings7
              )}
            >
              {"This is a really nice design!"}
            </div>
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px3"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px3}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px3)}
          >
            <IcMoreVertBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__gyDk6)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px4"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px4}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px4)}
          >
            <IcReplyBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__mBfcR)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"group5"}
            data-plasmic-override={overrides.group5}
            className={classNames(projectcss.all, sty.group5)}
          >
            <div
              data-plasmic-name={"settings8"}
              data-plasmic-override={overrides.settings8}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings8
              )}
            >
              {"notoyrobots"}
            </div>
            <div
              data-plasmic-name={"settings9"}
              data-plasmic-override={overrides.settings9}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings9
              )}
            >
              {"2 hours ago"}
            </div>
          </div>
          <div
            data-plasmic-name={"group6"}
            data-plasmic-override={overrides.group6}
            className={classNames(projectcss.all, sty.group6)}
          >
            <div
              data-plasmic-name={"settings10"}
              data-plasmic-override={overrides.settings10}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings10
              )}
            >
              {"1.5k"}
            </div>
            <Vector2Icon
              className={classNames(projectcss.all, sty.svg___8KVth)}
              role={"img"}
            />

            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__iQv8W)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"abefore2"}
            data-plasmic-override={overrides.abefore2}
            className={classNames(projectcss.all, sty.abefore2)}
          />
        </div>
        <div
          data-plasmic-name={"group7"}
          data-plasmic-override={overrides.group7}
          className={classNames(projectcss.all, sty.group7)}
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__sM5El)}
            displayHeight={"60px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"400px"}
            loading={"lazy"}
            src={{
              src: card18DqIos4XrT44M,
              fullWidth: 400,
              fullHeight: 60,
              aspectRatio: 6.666667
            }}
          />

          <div
            data-plasmic-name={"settings11"}
            data-plasmic-override={overrides.settings11}
            className={classNames(projectcss.all, sty.settings11)}
          >
            <div
              data-plasmic-name={"settings12"}
              data-plasmic-override={overrides.settings12}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings12
              )}
            >
              {"I already want to take my kids to the partk"}
            </div>
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px5"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px5}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px5)}
          >
            <IcMoreVertBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__fq1Xg)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px6"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px6}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px6)}
          >
            <IcReplyBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__jas9D)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"group8"}
            data-plasmic-override={overrides.group8}
            className={classNames(projectcss.all, sty.group8)}
          >
            <div
              data-plasmic-name={"settings13"}
              data-plasmic-override={overrides.settings13}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings13
              )}
            >
              {"notoyrobots"}
            </div>
            <div
              data-plasmic-name={"settings14"}
              data-plasmic-override={overrides.settings14}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings14
              )}
            >
              {"2 hours ago"}
            </div>
          </div>
          <div
            data-plasmic-name={"group9"}
            data-plasmic-override={overrides.group9}
            className={classNames(projectcss.all, sty.group9)}
          >
            <div
              data-plasmic-name={"settings15"}
              data-plasmic-override={overrides.settings15}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings15
              )}
            >
              {"1.5k"}
            </div>
            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__xwQa)}
              role={"img"}
            />

            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__ytnZb)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"abefore3"}
            data-plasmic-override={overrides.abefore3}
            className={classNames(projectcss.all, sty.abefore3)}
          />
        </div>
        <div
          data-plasmic-name={"group10"}
          data-plasmic-override={overrides.group10}
          className={classNames(projectcss.all, sty.group10)}
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__bfZx1)}
            displayHeight={"60px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"400px"}
            loading={"lazy"}
            src={{
              src: card17S1836A8Apxva,
              fullWidth: 400,
              fullHeight: 60,
              aspectRatio: 6.666667
            }}
          />

          <div
            data-plasmic-name={"settings16"}
            data-plasmic-override={overrides.settings16}
            className={classNames(projectcss.all, sty.settings16)}
          >
            <div
              data-plasmic-name={"settings17"}
              data-plasmic-override={overrides.settings17}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings17
              )}
            >
              {"Why do we need to renew the current bridge?"}
            </div>
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px7"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px7}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px7)}
          >
            <IcMoreVertBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__z5I3G)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px8"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px8}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px8)}
          >
            <IcReplyBlack24PxIcon
              className={classNames(projectcss.all, sty.svg___9Y2Ne)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"group11"}
            data-plasmic-override={overrides.group11}
            className={classNames(projectcss.all, sty.group11)}
          >
            <div
              data-plasmic-name={"settings18"}
              data-plasmic-override={overrides.settings18}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings18
              )}
            >
              {"notoyrobots"}
            </div>
            <div
              data-plasmic-name={"settings19"}
              data-plasmic-override={overrides.settings19}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings19
              )}
            >
              {"2 hours ago"}
            </div>
          </div>
          <div
            data-plasmic-name={"group12"}
            data-plasmic-override={overrides.group12}
            className={classNames(projectcss.all, sty.group12)}
          >
            <div
              data-plasmic-name={"settings20"}
              data-plasmic-override={overrides.settings20}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings20
              )}
            >
              {"1.5k"}
            </div>
            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__hP4KK)}
              role={"img"}
            />

            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__ocngN)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"abefore4"}
            data-plasmic-override={overrides.abefore4}
            className={classNames(projectcss.all, sty.abefore4)}
          />
        </div>
        <div
          data-plasmic-name={"group13"}
          data-plasmic-override={overrides.group13}
          className={classNames(projectcss.all, sty.group13)}
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__jcBqN)}
            displayHeight={"60px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"400px"}
            loading={"lazy"}
            src={{
              src: card16GVny4Zq83G7,
              fullWidth: 400,
              fullHeight: 60,
              aspectRatio: 6.666667
            }}
          />

          <div
            data-plasmic-name={"settings21"}
            data-plasmic-override={overrides.settings21}
            className={classNames(projectcss.all, sty.settings21)}
          >
            <div
              data-plasmic-name={"settings22"}
              data-plasmic-override={overrides.settings22}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings22
              )}
            >
              {"I will be happy driving through it daily"}
            </div>
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px9"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px9}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px9)}
          >
            <IcMoreVertBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__tf9Qo)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px10"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px10}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px10)}
          >
            <IcReplyBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__qAsNa)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"group14"}
            data-plasmic-override={overrides.group14}
            className={classNames(projectcss.all, sty.group14)}
          >
            <div
              data-plasmic-name={"settings23"}
              data-plasmic-override={overrides.settings23}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings23
              )}
            >
              {"notoyrobots"}
            </div>
            <div
              data-plasmic-name={"settings24"}
              data-plasmic-override={overrides.settings24}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings24
              )}
            >
              {"2 hours ago"}
            </div>
          </div>
          <div
            data-plasmic-name={"group15"}
            data-plasmic-override={overrides.group15}
            className={classNames(projectcss.all, sty.group15)}
          >
            <div
              data-plasmic-name={"settings25"}
              data-plasmic-override={overrides.settings25}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings25
              )}
            >
              {"1.5k"}
            </div>
            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__xts4B)}
              role={"img"}
            />

            <Vector2Icon
              className={classNames(projectcss.all, sty.svg___75M7M)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"abefore5"}
            data-plasmic-override={overrides.abefore5}
            className={classNames(projectcss.all, sty.abefore5)}
          />
        </div>
        <div
          data-plasmic-name={"enscape202312140837231"}
          data-plasmic-override={overrides.enscape202312140837231}
          className={classNames(projectcss.all, sty.enscape202312140837231)}
        />

        <div
          data-plasmic-name={"group16"}
          data-plasmic-override={overrides.group16}
          className={classNames(projectcss.all, sty.group16)}
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__spTdu)}
            displayHeight={"60px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"400px"}
            loading={"lazy"}
            src={{
              src: card153T5Hxzs8V4,
              fullWidth: 400,
              fullHeight: 60,
              aspectRatio: 6.666667
            }}
          />

          <div
            data-plasmic-name={"settings26"}
            data-plasmic-override={overrides.settings26}
            className={classNames(projectcss.all, sty.settings26)}
          >
            <div
              data-plasmic-name={"settings27"}
              data-plasmic-override={overrides.settings27}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings27
              )}
            >
              {"I can\u2019t wait until this gets done"}
            </div>
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px11"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px11}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px11)}
          >
            <IcMoreVertBlack24PxIcon
              className={classNames(projectcss.all, sty.svg___6K1Xu)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px12"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px12}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px12)}
          >
            <IcReplyBlack24PxIcon
              className={classNames(projectcss.all, sty.svg___7W9Q)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"group17"}
            data-plasmic-override={overrides.group17}
            className={classNames(projectcss.all, sty.group17)}
          >
            <div
              data-plasmic-name={"settings28"}
              data-plasmic-override={overrides.settings28}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings28
              )}
            >
              {"notoyrobots"}
            </div>
            <div
              data-plasmic-name={"settings29"}
              data-plasmic-override={overrides.settings29}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings29
              )}
            >
              {"2 hours ago"}
            </div>
          </div>
          <div
            data-plasmic-name={"group18"}
            data-plasmic-override={overrides.group18}
            className={classNames(projectcss.all, sty.group18)}
          >
            <div
              data-plasmic-name={"settings30"}
              data-plasmic-override={overrides.settings30}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings30
              )}
            >
              {"1.5k"}
            </div>
            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__zsosQ)}
              role={"img"}
            />

            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__vvoQm)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"abefore6"}
            data-plasmic-override={overrides.abefore6}
            className={classNames(projectcss.all, sty.abefore6)}
          />
        </div>
        <div
          data-plasmic-name={"group19"}
          data-plasmic-override={overrides.group19}
          className={classNames(projectcss.all, sty.group19)}
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__rrGiA)}
            displayHeight={"60px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"400px"}
            loading={"lazy"}
            src={{
              src: card14Q34VvSOLp6,
              fullWidth: 400,
              fullHeight: 60,
              aspectRatio: 6.666667
            }}
          />

          <div
            data-plasmic-name={"settings31"}
            data-plasmic-override={overrides.settings31}
            className={classNames(projectcss.all, sty.settings31)}
          >
            <div
              data-plasmic-name={"settings32"}
              data-plasmic-override={overrides.settings32}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings32
              )}
            >
              {"How long will the construction take?"}
            </div>
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px13"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px13}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px13)}
          >
            <IcMoreVertBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__frcSy)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px14"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px14}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px14)}
          >
            <IcReplyBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__vlgPj)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"group20"}
            data-plasmic-override={overrides.group20}
            className={classNames(projectcss.all, sty.group20)}
          >
            <div
              data-plasmic-name={"settings33"}
              data-plasmic-override={overrides.settings33}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings33
              )}
            >
              {"notoyrobots"}
            </div>
            <div
              data-plasmic-name={"settings34"}
              data-plasmic-override={overrides.settings34}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings34
              )}
            >
              {"2 hours ago"}
            </div>
          </div>
          <div
            data-plasmic-name={"group21"}
            data-plasmic-override={overrides.group21}
            className={classNames(projectcss.all, sty.group21)}
          >
            <div
              data-plasmic-name={"settings35"}
              data-plasmic-override={overrides.settings35}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings35
              )}
            >
              {"1.5k"}
            </div>
            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__uIrO)}
              role={"img"}
            />

            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__cVRY)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"abefore7"}
            data-plasmic-override={overrides.abefore7}
            className={classNames(projectcss.all, sty.abefore7)}
          />
        </div>
        <div
          data-plasmic-name={"group22"}
          data-plasmic-override={overrides.group22}
          className={classNames(projectcss.all, sty.group22)}
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img___3Dgcf)}
            displayHeight={"60px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"400px"}
            loading={"lazy"}
            src={{
              src: card13KtjFKvbQn3QE,
              fullWidth: 400,
              fullHeight: 60,
              aspectRatio: 6.666667
            }}
          />

          <div
            data-plasmic-name={"settings36"}
            data-plasmic-override={overrides.settings36}
            className={classNames(projectcss.all, sty.settings36)}
          >
            <div
              data-plasmic-name={"settings37"}
              data-plasmic-override={overrides.settings37}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings37
              )}
            >
              {"The view from here will be awesome!"}
            </div>
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px15"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px15}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px15)}
          >
            <IcMoreVertBlack24PxIcon
              className={classNames(projectcss.all, sty.svg___72Yf)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px16"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px16}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px16)}
          >
            <IcReplyBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__uG5P5)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"group23"}
            data-plasmic-override={overrides.group23}
            className={classNames(projectcss.all, sty.group23)}
          >
            <div
              data-plasmic-name={"settings38"}
              data-plasmic-override={overrides.settings38}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings38
              )}
            >
              {"notoyrobots"}
            </div>
            <div
              data-plasmic-name={"settings39"}
              data-plasmic-override={overrides.settings39}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings39
              )}
            >
              {"2 hours ago"}
            </div>
          </div>
          <div
            data-plasmic-name={"group24"}
            data-plasmic-override={overrides.group24}
            className={classNames(projectcss.all, sty.group24)}
          >
            <div
              data-plasmic-name={"settings40"}
              data-plasmic-override={overrides.settings40}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings40
              )}
            >
              {"1.5k"}
            </div>
            <Vector2Icon
              className={classNames(projectcss.all, sty.svg___2J19R)}
              role={"img"}
            />

            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__ukBxx)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"abefore8"}
            data-plasmic-override={overrides.abefore8}
            className={classNames(projectcss.all, sty.abefore8)}
          />
        </div>
        <div
          data-plasmic-name={"group25"}
          data-plasmic-override={overrides.group25}
          className={classNames(projectcss.all, sty.group25)}
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img___5QJ0Y)}
            displayHeight={"60px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"400px"}
            loading={"lazy"}
            src={{
              src: card12Hw0LkK0NawE9,
              fullWidth: 400,
              fullHeight: 60,
              aspectRatio: 6.666667
            }}
          />

          <div
            data-plasmic-name={"settings41"}
            data-plasmic-override={overrides.settings41}
            className={classNames(projectcss.all, sty.settings41)}
          >
            <div
              data-plasmic-name={"settings42"}
              data-plasmic-override={overrides.settings42}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings42
              )}
            >
              {"I like the white color"}
            </div>
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px17"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px17}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px17)}
          >
            <IcMoreVertBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__elp3B)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px18"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px18}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px18)}
          >
            <IcReplyBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__gMluk)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"group26"}
            data-plasmic-override={overrides.group26}
            className={classNames(projectcss.all, sty.group26)}
          >
            <div
              data-plasmic-name={"settings43"}
              data-plasmic-override={overrides.settings43}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings43
              )}
            >
              {"notoyrobots"}
            </div>
            <div
              data-plasmic-name={"settings44"}
              data-plasmic-override={overrides.settings44}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings44
              )}
            >
              {"2 hours ago"}
            </div>
          </div>
          <div
            data-plasmic-name={"group27"}
            data-plasmic-override={overrides.group27}
            className={classNames(projectcss.all, sty.group27)}
          >
            <div
              data-plasmic-name={"settings45"}
              data-plasmic-override={overrides.settings45}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings45
              )}
            >
              {"1.5k"}
            </div>
            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__xwea5)}
              role={"img"}
            />

            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__mv1Mk)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"abefore9"}
            data-plasmic-override={overrides.abefore9}
            className={classNames(projectcss.all, sty.abefore9)}
          />
        </div>
        <div
          data-plasmic-name={"group28"}
          data-plasmic-override={overrides.group28}
          className={classNames(projectcss.all, sty.group28)}
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img___2Fkg4)}
            displayHeight={"60px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"400px"}
            loading={"lazy"}
            src={{
              src: card11Go3TukYtRysD,
              fullWidth: 400,
              fullHeight: 60,
              aspectRatio: 6.666667
            }}
          />

          <div
            data-plasmic-name={"settings46"}
            data-plasmic-override={overrides.settings46}
            className={classNames(projectcss.all, sty.settings46)}
          >
            <div
              data-plasmic-name={"settings47"}
              data-plasmic-override={overrides.settings47}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings47
              )}
            >
              {"What are these blue things on the side?"}
            </div>
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px19"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px19}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px19)}
          >
            <IcMoreVertBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__pn1GY)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"icExpandMoreBlack24Px20"}
            data-plasmic-override={overrides.icExpandMoreBlack24Px20}
            className={classNames(projectcss.all, sty.icExpandMoreBlack24Px20)}
          >
            <IcReplyBlack24PxIcon
              className={classNames(projectcss.all, sty.svg__m90Da)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"group29"}
            data-plasmic-override={overrides.group29}
            className={classNames(projectcss.all, sty.group29)}
          >
            <div
              data-plasmic-name={"settings48"}
              data-plasmic-override={overrides.settings48}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings48
              )}
            >
              {"notoyrobots"}
            </div>
            <div
              data-plasmic-name={"settings49"}
              data-plasmic-override={overrides.settings49}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings49
              )}
            >
              {"2 hours ago"}
            </div>
          </div>
          <div
            data-plasmic-name={"group30"}
            data-plasmic-override={overrides.group30}
            className={classNames(projectcss.all, sty.group30)}
          >
            <div
              data-plasmic-name={"settings50"}
              data-plasmic-override={overrides.settings50}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.settings50
              )}
            >
              {"1.5k"}
            </div>
            <Vector2Icon
              className={classNames(projectcss.all, sty.svg___5BhN)}
              role={"img"}
            />

            <Vector2Icon
              className={classNames(projectcss.all, sty.svg__ol5IZ)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"abefore10"}
            data-plasmic-override={overrides.abefore10}
            className={classNames(projectcss.all, sty.abefore10)}
          />
        </div>
        <p.Stack
          as={"div"}
          data-plasmic-name={"viewSelectionBar"}
          data-plasmic-override={overrides.viewSelectionBar}
          hasGap={true}
          className={classNames(projectcss.all, sty.viewSelectionBar)}
        >
          <AntdButton
            data-plasmic-name={"button"}
            data-plasmic-override={overrides.button}
            className={classNames("__wab_instance", sty.button)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___3WvOj
              )}
            >
              {"Button"}
            </div>
          </AntdButton>
          <AntdButton
            data-plasmic-name={"frame8715"}
            data-plasmic-override={overrides.frame8715}
            className={classNames("__wab_instance", sty.frame8715)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__d0AVb
              )}
            >
              {"Button"}
            </div>
          </AntdButton>
          <AntdButton
            data-plasmic-name={"frame8716"}
            data-plasmic-override={overrides.frame8716}
            className={classNames("__wab_instance", sty.frame8716)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nyPht
              )}
            >
              {"Button"}
            </div>
          </AntdButton>
          <AntdButton
            data-plasmic-name={"frame8717"}
            data-plasmic-override={overrides.frame8717}
            className={classNames("__wab_instance", sty.frame8717)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__s60Yq
              )}
            >
              {"Button"}
            </div>
          </AntdButton>
          <AntdButton
            data-plasmic-name={"frame8718"}
            data-plasmic-override={overrides.frame8718}
            className={classNames("__wab_instance", sty.frame8718)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__q6Hi0
              )}
            >
              {"Button"}
            </div>
          </AntdButton>
        </p.Stack>
        <div
          data-plasmic-name={"chooseYourFavoriteProposal"}
          data-plasmic-override={overrides.chooseYourFavoriteProposal}
          className={classNames(projectcss.all, sty.chooseYourFavoriteProposal)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__bpIhN
            )}
          >
            {"Choose Your Favorite Proposal!"}
          </div>
        </div>
        <div
          data-plasmic-name={"section"}
          data-plasmic-override={overrides.section}
          className={classNames(projectcss.all, sty.section)}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"div"}
            data-plasmic-override={overrides.div}
            hasGap={true}
            className={classNames(projectcss.all, sty.div)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"votingCard"}
              data-plasmic-override={overrides.votingCard}
              hasGap={true}
              className={classNames(projectcss.all, sty.votingCard)}
            >
              <div
                data-plasmic-name={"h2"}
                data-plasmic-override={overrides.h2}
                className={classNames(projectcss.all, sty.h2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nlJBg
                  )}
                >
                  {"Proposal A"}
                </div>
              </div>
              <p.Stack
                as={"div"}
                data-plasmic-name={"div2"}
                data-plasmic-override={overrides.div2}
                hasGap={true}
                className={classNames(projectcss.all, sty.div2)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame8713"}
                  data-plasmic-override={overrides.frame8713}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame8713)}
                >
                  <div
                    data-plasmic-name={"votes"}
                    data-plasmic-override={overrides.votes}
                    className={classNames(projectcss.all, sty.votes)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wVRbg
                      )}
                    >
                      {"Votes:"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"_346"}
                    data-plasmic-override={overrides._346}
                    className={classNames(projectcss.all, sty._346)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3ZRkw
                      )}
                    >
                      {"346"}
                    </div>
                  </div>
                </p.Stack>
              </p.Stack>
              <div
                data-plasmic-name={"div3"}
                data-plasmic-override={overrides.div3}
                className={classNames(projectcss.all, sty.div3)}
              >
                <div
                  data-plasmic-name={"a"}
                  data-plasmic-override={overrides.a}
                  className={classNames(projectcss.all, sty.a)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__otUe
                    )}
                  >
                    {"Vote"}
                  </div>
                </div>
              </div>
            </p.Stack>
            <VotingCard
              data-plasmic-name={"votingCard2"}
              data-plasmic-override={overrides.votingCard2}
              className={classNames("__wab_instance", sty.votingCard2)}
            />

            <VotingCard
              data-plasmic-name={"votingCard3"}
              data-plasmic-override={overrides.votingCard3}
              className={classNames("__wab_instance", sty.votingCard3)}
            />

            <VotingCard
              data-plasmic-name={"votingCard4"}
              data-plasmic-override={overrides.votingCard4}
              className={classNames("__wab_instance", sty.votingCard4)}
            />

            <VotingCard
              data-plasmic-name={"votingCard5"}
              data-plasmic-override={overrides.votingCard5}
              className={classNames("__wab_instance", sty.votingCard5)}
            />
          </p.Stack>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "figmaPaste",
    "headerAndText",
    "navigationBar",
    "navigationBar2",
    "frame8722",
    "navigationButton",
    "rectangle7",
    "group",
    "settings",
    "settings2",
    "icExpandMoreBlack24Px",
    "icExpandMoreBlack24Px2",
    "group2",
    "settings3",
    "settings4",
    "group3",
    "settings5",
    "abefore",
    "group4",
    "settings6",
    "settings7",
    "icExpandMoreBlack24Px3",
    "icExpandMoreBlack24Px4",
    "group5",
    "settings8",
    "settings9",
    "group6",
    "settings10",
    "abefore2",
    "group7",
    "settings11",
    "settings12",
    "icExpandMoreBlack24Px5",
    "icExpandMoreBlack24Px6",
    "group8",
    "settings13",
    "settings14",
    "group9",
    "settings15",
    "abefore3",
    "group10",
    "settings16",
    "settings17",
    "icExpandMoreBlack24Px7",
    "icExpandMoreBlack24Px8",
    "group11",
    "settings18",
    "settings19",
    "group12",
    "settings20",
    "abefore4",
    "group13",
    "settings21",
    "settings22",
    "icExpandMoreBlack24Px9",
    "icExpandMoreBlack24Px10",
    "group14",
    "settings23",
    "settings24",
    "group15",
    "settings25",
    "abefore5",
    "enscape202312140837231",
    "group16",
    "settings26",
    "settings27",
    "icExpandMoreBlack24Px11",
    "icExpandMoreBlack24Px12",
    "group17",
    "settings28",
    "settings29",
    "group18",
    "settings30",
    "abefore6",
    "group19",
    "settings31",
    "settings32",
    "icExpandMoreBlack24Px13",
    "icExpandMoreBlack24Px14",
    "group20",
    "settings33",
    "settings34",
    "group21",
    "settings35",
    "abefore7",
    "group22",
    "settings36",
    "settings37",
    "icExpandMoreBlack24Px15",
    "icExpandMoreBlack24Px16",
    "group23",
    "settings38",
    "settings39",
    "group24",
    "settings40",
    "abefore8",
    "group25",
    "settings41",
    "settings42",
    "icExpandMoreBlack24Px17",
    "icExpandMoreBlack24Px18",
    "group26",
    "settings43",
    "settings44",
    "group27",
    "settings45",
    "abefore9",
    "group28",
    "settings46",
    "settings47",
    "icExpandMoreBlack24Px19",
    "icExpandMoreBlack24Px20",
    "group29",
    "settings48",
    "settings49",
    "group30",
    "settings50",
    "abefore10",
    "viewSelectionBar",
    "button",
    "frame8715",
    "frame8716",
    "frame8717",
    "frame8718",
    "chooseYourFavoriteProposal",
    "section",
    "div",
    "votingCard",
    "h2",
    "div2",
    "frame8713",
    "votes",
    "_346",
    "div3",
    "a",
    "votingCard2",
    "votingCard3",
    "votingCard4",
    "votingCard5"
  ],

  figmaPaste: [
    "figmaPaste",
    "headerAndText",
    "navigationBar",
    "navigationBar2",
    "frame8722",
    "navigationButton",
    "rectangle7",
    "group",
    "settings",
    "settings2",
    "icExpandMoreBlack24Px",
    "icExpandMoreBlack24Px2",
    "group2",
    "settings3",
    "settings4",
    "group3",
    "settings5",
    "abefore",
    "group4",
    "settings6",
    "settings7",
    "icExpandMoreBlack24Px3",
    "icExpandMoreBlack24Px4",
    "group5",
    "settings8",
    "settings9",
    "group6",
    "settings10",
    "abefore2",
    "group7",
    "settings11",
    "settings12",
    "icExpandMoreBlack24Px5",
    "icExpandMoreBlack24Px6",
    "group8",
    "settings13",
    "settings14",
    "group9",
    "settings15",
    "abefore3",
    "group10",
    "settings16",
    "settings17",
    "icExpandMoreBlack24Px7",
    "icExpandMoreBlack24Px8",
    "group11",
    "settings18",
    "settings19",
    "group12",
    "settings20",
    "abefore4",
    "group13",
    "settings21",
    "settings22",
    "icExpandMoreBlack24Px9",
    "icExpandMoreBlack24Px10",
    "group14",
    "settings23",
    "settings24",
    "group15",
    "settings25",
    "abefore5",
    "enscape202312140837231",
    "group16",
    "settings26",
    "settings27",
    "icExpandMoreBlack24Px11",
    "icExpandMoreBlack24Px12",
    "group17",
    "settings28",
    "settings29",
    "group18",
    "settings30",
    "abefore6",
    "group19",
    "settings31",
    "settings32",
    "icExpandMoreBlack24Px13",
    "icExpandMoreBlack24Px14",
    "group20",
    "settings33",
    "settings34",
    "group21",
    "settings35",
    "abefore7",
    "group22",
    "settings36",
    "settings37",
    "icExpandMoreBlack24Px15",
    "icExpandMoreBlack24Px16",
    "group23",
    "settings38",
    "settings39",
    "group24",
    "settings40",
    "abefore8",
    "group25",
    "settings41",
    "settings42",
    "icExpandMoreBlack24Px17",
    "icExpandMoreBlack24Px18",
    "group26",
    "settings43",
    "settings44",
    "group27",
    "settings45",
    "abefore9",
    "group28",
    "settings46",
    "settings47",
    "icExpandMoreBlack24Px19",
    "icExpandMoreBlack24Px20",
    "group29",
    "settings48",
    "settings49",
    "group30",
    "settings50",
    "abefore10",
    "viewSelectionBar",
    "button",
    "frame8715",
    "frame8716",
    "frame8717",
    "frame8718",
    "chooseYourFavoriteProposal",
    "section",
    "div",
    "votingCard",
    "h2",
    "div2",
    "frame8713",
    "votes",
    "_346",
    "div3",
    "a",
    "votingCard2",
    "votingCard3",
    "votingCard4",
    "votingCard5"
  ],

  headerAndText: ["headerAndText"],
  navigationBar: ["navigationBar", "navigationBar2"],
  navigationBar2: ["navigationBar2"],
  frame8722: ["frame8722", "navigationButton", "rectangle7"],
  navigationButton: ["navigationButton", "rectangle7"],
  rectangle7: ["rectangle7"],
  group: [
    "group",
    "settings",
    "settings2",
    "icExpandMoreBlack24Px",
    "icExpandMoreBlack24Px2",
    "group2",
    "settings3",
    "settings4",
    "group3",
    "settings5",
    "abefore"
  ],

  settings: ["settings", "settings2"],
  settings2: ["settings2"],
  icExpandMoreBlack24Px: ["icExpandMoreBlack24Px"],
  icExpandMoreBlack24Px2: ["icExpandMoreBlack24Px2"],
  group2: ["group2", "settings3", "settings4"],
  settings3: ["settings3"],
  settings4: ["settings4"],
  group3: ["group3", "settings5"],
  settings5: ["settings5"],
  abefore: ["abefore"],
  group4: [
    "group4",
    "settings6",
    "settings7",
    "icExpandMoreBlack24Px3",
    "icExpandMoreBlack24Px4",
    "group5",
    "settings8",
    "settings9",
    "group6",
    "settings10",
    "abefore2"
  ],

  settings6: ["settings6", "settings7"],
  settings7: ["settings7"],
  icExpandMoreBlack24Px3: ["icExpandMoreBlack24Px3"],
  icExpandMoreBlack24Px4: ["icExpandMoreBlack24Px4"],
  group5: ["group5", "settings8", "settings9"],
  settings8: ["settings8"],
  settings9: ["settings9"],
  group6: ["group6", "settings10"],
  settings10: ["settings10"],
  abefore2: ["abefore2"],
  group7: [
    "group7",
    "settings11",
    "settings12",
    "icExpandMoreBlack24Px5",
    "icExpandMoreBlack24Px6",
    "group8",
    "settings13",
    "settings14",
    "group9",
    "settings15",
    "abefore3"
  ],

  settings11: ["settings11", "settings12"],
  settings12: ["settings12"],
  icExpandMoreBlack24Px5: ["icExpandMoreBlack24Px5"],
  icExpandMoreBlack24Px6: ["icExpandMoreBlack24Px6"],
  group8: ["group8", "settings13", "settings14"],
  settings13: ["settings13"],
  settings14: ["settings14"],
  group9: ["group9", "settings15"],
  settings15: ["settings15"],
  abefore3: ["abefore3"],
  group10: [
    "group10",
    "settings16",
    "settings17",
    "icExpandMoreBlack24Px7",
    "icExpandMoreBlack24Px8",
    "group11",
    "settings18",
    "settings19",
    "group12",
    "settings20",
    "abefore4"
  ],

  settings16: ["settings16", "settings17"],
  settings17: ["settings17"],
  icExpandMoreBlack24Px7: ["icExpandMoreBlack24Px7"],
  icExpandMoreBlack24Px8: ["icExpandMoreBlack24Px8"],
  group11: ["group11", "settings18", "settings19"],
  settings18: ["settings18"],
  settings19: ["settings19"],
  group12: ["group12", "settings20"],
  settings20: ["settings20"],
  abefore4: ["abefore4"],
  group13: [
    "group13",
    "settings21",
    "settings22",
    "icExpandMoreBlack24Px9",
    "icExpandMoreBlack24Px10",
    "group14",
    "settings23",
    "settings24",
    "group15",
    "settings25",
    "abefore5"
  ],

  settings21: ["settings21", "settings22"],
  settings22: ["settings22"],
  icExpandMoreBlack24Px9: ["icExpandMoreBlack24Px9"],
  icExpandMoreBlack24Px10: ["icExpandMoreBlack24Px10"],
  group14: ["group14", "settings23", "settings24"],
  settings23: ["settings23"],
  settings24: ["settings24"],
  group15: ["group15", "settings25"],
  settings25: ["settings25"],
  abefore5: ["abefore5"],
  enscape202312140837231: ["enscape202312140837231"],
  group16: [
    "group16",
    "settings26",
    "settings27",
    "icExpandMoreBlack24Px11",
    "icExpandMoreBlack24Px12",
    "group17",
    "settings28",
    "settings29",
    "group18",
    "settings30",
    "abefore6"
  ],

  settings26: ["settings26", "settings27"],
  settings27: ["settings27"],
  icExpandMoreBlack24Px11: ["icExpandMoreBlack24Px11"],
  icExpandMoreBlack24Px12: ["icExpandMoreBlack24Px12"],
  group17: ["group17", "settings28", "settings29"],
  settings28: ["settings28"],
  settings29: ["settings29"],
  group18: ["group18", "settings30"],
  settings30: ["settings30"],
  abefore6: ["abefore6"],
  group19: [
    "group19",
    "settings31",
    "settings32",
    "icExpandMoreBlack24Px13",
    "icExpandMoreBlack24Px14",
    "group20",
    "settings33",
    "settings34",
    "group21",
    "settings35",
    "abefore7"
  ],

  settings31: ["settings31", "settings32"],
  settings32: ["settings32"],
  icExpandMoreBlack24Px13: ["icExpandMoreBlack24Px13"],
  icExpandMoreBlack24Px14: ["icExpandMoreBlack24Px14"],
  group20: ["group20", "settings33", "settings34"],
  settings33: ["settings33"],
  settings34: ["settings34"],
  group21: ["group21", "settings35"],
  settings35: ["settings35"],
  abefore7: ["abefore7"],
  group22: [
    "group22",
    "settings36",
    "settings37",
    "icExpandMoreBlack24Px15",
    "icExpandMoreBlack24Px16",
    "group23",
    "settings38",
    "settings39",
    "group24",
    "settings40",
    "abefore8"
  ],

  settings36: ["settings36", "settings37"],
  settings37: ["settings37"],
  icExpandMoreBlack24Px15: ["icExpandMoreBlack24Px15"],
  icExpandMoreBlack24Px16: ["icExpandMoreBlack24Px16"],
  group23: ["group23", "settings38", "settings39"],
  settings38: ["settings38"],
  settings39: ["settings39"],
  group24: ["group24", "settings40"],
  settings40: ["settings40"],
  abefore8: ["abefore8"],
  group25: [
    "group25",
    "settings41",
    "settings42",
    "icExpandMoreBlack24Px17",
    "icExpandMoreBlack24Px18",
    "group26",
    "settings43",
    "settings44",
    "group27",
    "settings45",
    "abefore9"
  ],

  settings41: ["settings41", "settings42"],
  settings42: ["settings42"],
  icExpandMoreBlack24Px17: ["icExpandMoreBlack24Px17"],
  icExpandMoreBlack24Px18: ["icExpandMoreBlack24Px18"],
  group26: ["group26", "settings43", "settings44"],
  settings43: ["settings43"],
  settings44: ["settings44"],
  group27: ["group27", "settings45"],
  settings45: ["settings45"],
  abefore9: ["abefore9"],
  group28: [
    "group28",
    "settings46",
    "settings47",
    "icExpandMoreBlack24Px19",
    "icExpandMoreBlack24Px20",
    "group29",
    "settings48",
    "settings49",
    "group30",
    "settings50",
    "abefore10"
  ],

  settings46: ["settings46", "settings47"],
  settings47: ["settings47"],
  icExpandMoreBlack24Px19: ["icExpandMoreBlack24Px19"],
  icExpandMoreBlack24Px20: ["icExpandMoreBlack24Px20"],
  group29: ["group29", "settings48", "settings49"],
  settings48: ["settings48"],
  settings49: ["settings49"],
  group30: ["group30", "settings50"],
  settings50: ["settings50"],
  abefore10: ["abefore10"],
  viewSelectionBar: [
    "viewSelectionBar",
    "button",
    "frame8715",
    "frame8716",
    "frame8717",
    "frame8718"
  ],

  button: ["button"],
  frame8715: ["frame8715"],
  frame8716: ["frame8716"],
  frame8717: ["frame8717"],
  frame8718: ["frame8718"],
  chooseYourFavoriteProposal: ["chooseYourFavoriteProposal"],
  section: [
    "section",
    "div",
    "votingCard",
    "h2",
    "div2",
    "frame8713",
    "votes",
    "_346",
    "div3",
    "a",
    "votingCard2",
    "votingCard3",
    "votingCard4",
    "votingCard5"
  ],

  div: [
    "div",
    "votingCard",
    "h2",
    "div2",
    "frame8713",
    "votes",
    "_346",
    "div3",
    "a",
    "votingCard2",
    "votingCard3",
    "votingCard4",
    "votingCard5"
  ],

  votingCard: [
    "votingCard",
    "h2",
    "div2",
    "frame8713",
    "votes",
    "_346",
    "div3",
    "a"
  ],

  h2: ["h2"],
  div2: ["div2", "frame8713", "votes", "_346"],
  frame8713: ["frame8713", "votes", "_346"],
  votes: ["votes"],
  _346: ["_346"],
  div3: ["div3", "a"],
  a: ["a"],
  votingCard2: ["votingCard2"],
  votingCard3: ["votingCard3"],
  votingCard4: ["votingCard4"],
  votingCard5: ["votingCard5"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicModelViewer__ArgProps,
          internalVariantPropNames: PlasmicModelViewer__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicModelViewer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicModelViewer";
  } else {
    func.displayName = `PlasmicModelViewer.${nodeName}`;
  }
  return func;
}

export const PlasmicModelViewer = Object.assign(
  // Top-level PlasmicModelViewer renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    figmaPaste: makeNodeComponent("figmaPaste"),
    headerAndText: makeNodeComponent("headerAndText"),
    navigationBar: makeNodeComponent("navigationBar"),
    navigationBar2: makeNodeComponent("navigationBar2"),
    frame8722: makeNodeComponent("frame8722"),
    navigationButton: makeNodeComponent("navigationButton"),
    rectangle7: makeNodeComponent("rectangle7"),
    group: makeNodeComponent("group"),
    settings: makeNodeComponent("settings"),
    settings2: makeNodeComponent("settings2"),
    icExpandMoreBlack24Px: makeNodeComponent("icExpandMoreBlack24Px"),
    icExpandMoreBlack24Px2: makeNodeComponent("icExpandMoreBlack24Px2"),
    group2: makeNodeComponent("group2"),
    settings3: makeNodeComponent("settings3"),
    settings4: makeNodeComponent("settings4"),
    group3: makeNodeComponent("group3"),
    settings5: makeNodeComponent("settings5"),
    abefore: makeNodeComponent("abefore"),
    group4: makeNodeComponent("group4"),
    settings6: makeNodeComponent("settings6"),
    settings7: makeNodeComponent("settings7"),
    icExpandMoreBlack24Px3: makeNodeComponent("icExpandMoreBlack24Px3"),
    icExpandMoreBlack24Px4: makeNodeComponent("icExpandMoreBlack24Px4"),
    group5: makeNodeComponent("group5"),
    settings8: makeNodeComponent("settings8"),
    settings9: makeNodeComponent("settings9"),
    group6: makeNodeComponent("group6"),
    settings10: makeNodeComponent("settings10"),
    abefore2: makeNodeComponent("abefore2"),
    group7: makeNodeComponent("group7"),
    settings11: makeNodeComponent("settings11"),
    settings12: makeNodeComponent("settings12"),
    icExpandMoreBlack24Px5: makeNodeComponent("icExpandMoreBlack24Px5"),
    icExpandMoreBlack24Px6: makeNodeComponent("icExpandMoreBlack24Px6"),
    group8: makeNodeComponent("group8"),
    settings13: makeNodeComponent("settings13"),
    settings14: makeNodeComponent("settings14"),
    group9: makeNodeComponent("group9"),
    settings15: makeNodeComponent("settings15"),
    abefore3: makeNodeComponent("abefore3"),
    group10: makeNodeComponent("group10"),
    settings16: makeNodeComponent("settings16"),
    settings17: makeNodeComponent("settings17"),
    icExpandMoreBlack24Px7: makeNodeComponent("icExpandMoreBlack24Px7"),
    icExpandMoreBlack24Px8: makeNodeComponent("icExpandMoreBlack24Px8"),
    group11: makeNodeComponent("group11"),
    settings18: makeNodeComponent("settings18"),
    settings19: makeNodeComponent("settings19"),
    group12: makeNodeComponent("group12"),
    settings20: makeNodeComponent("settings20"),
    abefore4: makeNodeComponent("abefore4"),
    group13: makeNodeComponent("group13"),
    settings21: makeNodeComponent("settings21"),
    settings22: makeNodeComponent("settings22"),
    icExpandMoreBlack24Px9: makeNodeComponent("icExpandMoreBlack24Px9"),
    icExpandMoreBlack24Px10: makeNodeComponent("icExpandMoreBlack24Px10"),
    group14: makeNodeComponent("group14"),
    settings23: makeNodeComponent("settings23"),
    settings24: makeNodeComponent("settings24"),
    group15: makeNodeComponent("group15"),
    settings25: makeNodeComponent("settings25"),
    abefore5: makeNodeComponent("abefore5"),
    enscape202312140837231: makeNodeComponent("enscape202312140837231"),
    group16: makeNodeComponent("group16"),
    settings26: makeNodeComponent("settings26"),
    settings27: makeNodeComponent("settings27"),
    icExpandMoreBlack24Px11: makeNodeComponent("icExpandMoreBlack24Px11"),
    icExpandMoreBlack24Px12: makeNodeComponent("icExpandMoreBlack24Px12"),
    group17: makeNodeComponent("group17"),
    settings28: makeNodeComponent("settings28"),
    settings29: makeNodeComponent("settings29"),
    group18: makeNodeComponent("group18"),
    settings30: makeNodeComponent("settings30"),
    abefore6: makeNodeComponent("abefore6"),
    group19: makeNodeComponent("group19"),
    settings31: makeNodeComponent("settings31"),
    settings32: makeNodeComponent("settings32"),
    icExpandMoreBlack24Px13: makeNodeComponent("icExpandMoreBlack24Px13"),
    icExpandMoreBlack24Px14: makeNodeComponent("icExpandMoreBlack24Px14"),
    group20: makeNodeComponent("group20"),
    settings33: makeNodeComponent("settings33"),
    settings34: makeNodeComponent("settings34"),
    group21: makeNodeComponent("group21"),
    settings35: makeNodeComponent("settings35"),
    abefore7: makeNodeComponent("abefore7"),
    group22: makeNodeComponent("group22"),
    settings36: makeNodeComponent("settings36"),
    settings37: makeNodeComponent("settings37"),
    icExpandMoreBlack24Px15: makeNodeComponent("icExpandMoreBlack24Px15"),
    icExpandMoreBlack24Px16: makeNodeComponent("icExpandMoreBlack24Px16"),
    group23: makeNodeComponent("group23"),
    settings38: makeNodeComponent("settings38"),
    settings39: makeNodeComponent("settings39"),
    group24: makeNodeComponent("group24"),
    settings40: makeNodeComponent("settings40"),
    abefore8: makeNodeComponent("abefore8"),
    group25: makeNodeComponent("group25"),
    settings41: makeNodeComponent("settings41"),
    settings42: makeNodeComponent("settings42"),
    icExpandMoreBlack24Px17: makeNodeComponent("icExpandMoreBlack24Px17"),
    icExpandMoreBlack24Px18: makeNodeComponent("icExpandMoreBlack24Px18"),
    group26: makeNodeComponent("group26"),
    settings43: makeNodeComponent("settings43"),
    settings44: makeNodeComponent("settings44"),
    group27: makeNodeComponent("group27"),
    settings45: makeNodeComponent("settings45"),
    abefore9: makeNodeComponent("abefore9"),
    group28: makeNodeComponent("group28"),
    settings46: makeNodeComponent("settings46"),
    settings47: makeNodeComponent("settings47"),
    icExpandMoreBlack24Px19: makeNodeComponent("icExpandMoreBlack24Px19"),
    icExpandMoreBlack24Px20: makeNodeComponent("icExpandMoreBlack24Px20"),
    group29: makeNodeComponent("group29"),
    settings48: makeNodeComponent("settings48"),
    settings49: makeNodeComponent("settings49"),
    group30: makeNodeComponent("group30"),
    settings50: makeNodeComponent("settings50"),
    abefore10: makeNodeComponent("abefore10"),
    viewSelectionBar: makeNodeComponent("viewSelectionBar"),
    button: makeNodeComponent("button"),
    frame8715: makeNodeComponent("frame8715"),
    frame8716: makeNodeComponent("frame8716"),
    frame8717: makeNodeComponent("frame8717"),
    frame8718: makeNodeComponent("frame8718"),
    chooseYourFavoriteProposal: makeNodeComponent("chooseYourFavoriteProposal"),
    section: makeNodeComponent("section"),
    div: makeNodeComponent("div"),
    votingCard: makeNodeComponent("votingCard"),
    h2: makeNodeComponent("h2"),
    div2: makeNodeComponent("div2"),
    frame8713: makeNodeComponent("frame8713"),
    votes: makeNodeComponent("votes"),
    _346: makeNodeComponent("_346"),
    div3: makeNodeComponent("div3"),
    a: makeNodeComponent("a"),
    votingCard2: makeNodeComponent("votingCard2"),
    votingCard3: makeNodeComponent("votingCard3"),
    votingCard4: makeNodeComponent("votingCard4"),
    votingCard5: makeNodeComponent("votingCard5"),
    // Metadata about props expected for PlasmicModelViewer
    internalVariantProps: PlasmicModelViewer__VariantProps,
    internalArgProps: PlasmicModelViewer__ArgProps
  }
);

export default PlasmicModelViewer;
/* prettier-ignore-end */
